use hanpost;

CREATE TABLE IF NOT EXISTS posts (
	id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    text_content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS post_images (
	id INT AUTO_INCREMENT PRIMARY KEY,
	post_id INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    image_order INT,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);
